/**
 * One-off: hand-corrected JSON + PDF for E-Way Bill 562032154192,
 * transcribed directly from the source photo (the Groq vision extraction
 * misread several fields on this image). Does not touch the live
 * llmExtract/pdfBuilder pipeline.
 */
import fs from "fs";
import path from "path";
import PDFDocument from "pdfkit";
import QRCode from "qrcode";
import bwipjs from "bwip-js";

const DATA = {
  document_type: "E-Way Bill",
  eway_bill_no: "562032154192",
  status: "EWB (Active)",
  summary: {
    eway_bill_date: "04/07/2026 08:16:00 PM",
    generated_by: { gstin: "33AABCG3365J1ZP", name: "Godrej Consumer Products Ltd" },
    valid_from: "04/07/2026 08:16:00 PM",
    distance_km: 548,
    valid_until: "07/07/2026",
    portal: "1",
  },
  irn_details: {
    irn: "529c241ceb5be4f0a54aa3e9cc95f7474a2daaf503129c8a870b2bbbcf557846",
    irn_date: "04/07/2026 08:16:00 PM",
    ack_no: "152626321182645",
  },
  part_a: {
    supplier: { gstin: "33AABCG3365J1ZP", name: "Godrej Consumer Products Ltd" },
    place_of_dispatch:
      "PANCHAVADI, RS NO 25/1A1A, ANNA NAGAR, ACHARAMPATTUL, village Thiruchitrambalam Post, Vanur Taluk, Villupuram, TAMIL NADU, 605111",
    recipient: { gstin: "32AABCG3365J1ZR", name: "Godrej Consumer Products Ltd-Cochin" },
    place_of_delivery:
      "Building No XXI/727, Nochima Nad PO, Aluva, Cochin-683563, Aluva, KERALA, 683563",
    document_no: "BOSTN35200221",
    document_date: "04/07/2026",
    transaction_type: "Regular",
    value_of_goods: 20160.0,
    hsn_code: "40141010",
    hsn_description: "KS10'S RIBBED M100 P480 NEWAW",
    reason_for_transportation: "Outward - Supply",
    transporter: { id: "09AASCS0150N1ZU", name: "S S FORWARDERS PRIVATE LIMITED" },
  },
  part_b: [
    {
      mode: "Road",
      vehicle_trans_doc_no_and_dt: "TN72CL6728 / 66111 & 04/07/2026",
      from: "Villupuram",
      entered_date: "04/07/2026 08:16:00 PM",
      entered_by: "33AABCG3365J1ZP",
      cewb_no: null,
      multi_vehicle_info: null,
      portal: "1",
    },
  ],
  barcode_value: "562032154192",
};

function gstinName(d: any): string {
  d = d || {};
  return `${d.gstin || ""},${String(d.name || "").toUpperCase()}`;
}

async function renderCorrectedPdf(DATA: any): Promise<Buffer> {
  const s = DATA.summary || {};
  const a = DATA.part_a || {};
  const irnD = DATA.irn_details || {};
  const ewb = String(DATA.eway_bill_no || "");
  const gen = s.generated_by || {};

  const qrPayload = `${ewb}/${gen.gstin || ""}/${s.eway_bill_date || ""}`;
  const qrBuf = await QRCode.toBuffer(qrPayload, { margin: 1, width: 130 });
  const bcBuf: Buffer = await bwipjs.toBuffer({
    bcid: "code128",
    text: ewb || "0",
    scale: 2,
    height: 11,
    includetext: false,
  });

  const doc = new PDFDocument({ size: "A4", margins: { top: 28, bottom: 28, left: 40, right: 40 } });
  const chunks: Buffer[] = [];
  doc.on("data", (c: Buffer) => chunks.push(c));
  const done = new Promise<Buffer>((resolve) => doc.on("end", () => resolve(Buffer.concat(chunks))));

  const left = doc.page.margins.left;
  const right = doc.page.width - doc.page.margins.right;
  const width = right - left;
  let y = doc.page.margins.top;

  doc.font("Helvetica-Bold").fontSize(16).fillColor("#000").text("e-Way Bill", left, y, { width, align: "center" });
  y += 24;
  doc.image(qrBuf, left + width / 2 - 45, y, { width: 90, height: 90 });
  y += 100;

  const labelW = 150;
  const valW = width - labelW;

  const row = (label: string, value: any) => {
    const v = String(value ?? "");
    const lh = doc.font("Helvetica").fontSize(9).heightOfString(label, { width: labelW - 8 });
    const vh = doc.font("Helvetica-Bold").fontSize(9).heightOfString(v, { width: valW - 8 });
    const h = Math.max(18, lh, vh) + 6;
    doc.lineWidth(0.5);
    doc.rect(left, y, labelW, h).stroke("#000");
    doc.rect(left + labelW, y, valW, h).stroke("#000");
    doc.font("Helvetica").fontSize(9).fillColor("#000").text(label, left + 4, y + 4, { width: labelW - 8 });
    doc.font("Helvetica-Bold").fontSize(9).text(v, left + labelW + 4, y + 4, { width: valW - 8 });
    y += h;
  };

  const section = (text: string) => {
    const h = 18;
    doc.rect(left, y, width, h).fillAndStroke("#f0f0f0", "#000");
    doc.fillColor("#000").font("Helvetica-Bold").fontSize(9).text(text, left + 4, y + 5, { width: width - 8 });
    y += h;
  };

  const distSuffix = s.distance_km ? ` [${s.distance_km}Kms]` : "";

  row("E-Way Bill No:", ewb);
  row("E-Way Bill Date:", s.eway_bill_date || "");
  row("E-Way Bill Status:", DATA.status || "");
  row("Generated By:", `${gen.gstin || ""} - ${String(gen.name || "").toUpperCase()}`);
  row("Valid From:", `${s.valid_from || ""}${distSuffix}`);
  row("Valid Until:", s.valid_until || "");
  row("Portal:", s.portal || "1");

  section("IRN Details");
  row("IRN:", irnD.irn || "");
  row("IRN Date:", irnD.irn_date || "");
  row("Ack No.:", irnD.ack_no || "");

  section("Part - A");
  row("GSTIN of Supplier", gstinName(a.supplier));
  row("Place of Dispatch", a.place_of_dispatch || "");
  row("GSTIN of Recipient", gstinName(a.recipient));
  row("Place of Delivery", a.place_of_delivery || "");
  row("Document No.", a.document_no || "");
  row("Document Date", a.document_date || "");
  row("Transaction Type:", a.transaction_type || "");
  row("Value of Goods", a.value_of_goods ?? "");
  row("HSN Code", `${a.hsn_code || ""} - ${a.hsn_description || ""}`);
  row("Reason for Transportation", a.reason_for_transportation || "");
  const tr = a.transporter || {};
  row("Transporter", `${tr.id || ""} & ${tr.name || ""}`);

  section("Part - B");

  const headers = ["Mode", "Vehicle / Trans Doc No & Dt.", "From", "Entered Date", "Entered By", "CEWB", "Multi Veh", "Portal"];
  const cw = [40, 110, 55, 80, 80, 40, 40, 30];
  const scale = width / cw.reduce((p, c) => p + c, 0);
  const colW = cw.map((w) => w * scale);

  const drawTableRow = (cells: string[], bold: boolean, fill?: string) => {
    let h = 16;
    cells.forEach((c, i) => {
      const ch = doc.font(bold ? "Helvetica-Bold" : "Helvetica").fontSize(7.5).heightOfString(c, { width: colW[i] - 6 });
      h = Math.max(h, ch + 6);
    });
    let x = left;
    cells.forEach((c, i) => {
      if (fill) doc.rect(x, y, colW[i], h).fillAndStroke(fill, "#000");
      else doc.rect(x, y, colW[i], h).stroke("#000");
      doc.fillColor("#000").font(bold ? "Helvetica-Bold" : "Helvetica").fontSize(7.5)
        .text(c, x + 3, y + 3, { width: colW[i] - 6 });
      x += colW[i];
    });
    y += h;
  };

  drawTableRow(headers, true, "#f0f0f0");
  for (const r of DATA.part_b || []) {
    drawTableRow(
      [
        String(r.mode || ""),
        String(r.vehicle_trans_doc_no_and_dt || ""),
        String(r.from || ""),
        String(r.entered_date || ""),
        String(r.entered_by || ""),
        String(r.cewb_no ?? "-"),
        String(r.multi_vehicle_info ?? "-"),
        String(r.portal || "1"),
      ],
      false
    );
  }

  y += 14;
  doc.image(bcBuf, left + width / 2 - 70, y, { width: 140, height: 32 });
  y += 34;
  doc.font("Helvetica").fontSize(8).text(ewb, left, y, { width, align: "center" });
  y += 16;

  doc.font("Helvetica").fontSize(7).fillColor("#333")
    .text("Note*: If any discrepancy in information please try after sometimes.", left, y, { width });

  doc.end();
  return await done;
}

(async () => {
  const outDir = path.join(__dirname, "..", "outputs");
  fs.mkdirSync(outDir, { recursive: true });
  const jsonPath = path.join(outDir, `${DATA.eway_bill_no}.json`);
  const pdfPath = path.join(outDir, `${DATA.eway_bill_no}_eway.pdf`);
  fs.writeFileSync(jsonPath, JSON.stringify(DATA, null, 2));
  const buf = await renderCorrectedPdf(DATA);
  fs.writeFileSync(pdfPath, buf);
  console.log("Wrote:", jsonPath);
  console.log("Wrote:", pdfPath);
})();
